### ISSUE TITLE
Creating new users fails with 400 error

### ISSUE THREAD

**Issue by faith-mutua** [onaio/kaznet-frontend#261]
**Expected behavior**
Admins should be able to create users with different roles and levels of expertise in the kaznet web app. 

**Actual behavior**
Creating users in the kaznet web app fails with a 400 error in the console log. 

**Steps to reproduce**
- Create a user and assign any role/level of expertise.

**Comment by faith-mutua** [comment]
related to https://github.com/onaio/kaznet-web/issues/338

**Comment by katherine95** [comment]
@faith-mutua I would love to work on this issue.

**Comment by katherine95** [comment]
@faith-mutua is it okay if I go ahead with this? Although I noticed contributors must be given access first to the API.

**Comment by moshthepitt** [comment]
> Although I noticed contributors must be given access first to the API.

@katherine95 what do you mean by this?

**Comment by katherine95** [comment]
@moshthepitt when mounting the users component, it tries accessing a user's token(but am a new user). I haven't managed to view the frontend UI since I started setting up. Below is a screenshot of the console.
<img width="1436" alt="Screenshot 2019-10-03 at 15 47 01" src="https://user-images.githubusercontent.com/17095461/66127905-696cd880-e5f5-11e9-878c-dbceb2f71c8d.png">

**Comment by moshthepitt** [comment]
The frontend needs the following to work:

- you need to have set up its backend https://github.com/onaio/kaznet-web with the right settings
- you need to set up the front end with valid working settings that point to the backend
